CC = clang

.PHONY: clean all

all: HW_3_Q3 HW_3_Q4

HW_3_Q3: HW_3_Q3.o
	$(CC) -o HW_3_Q3 HW_3_Q3.o

HW_3_Q3.o: HW_3_Q3.c
	$(CC) -c HW_3_Q3.c

HW_3_Q4: HW_3_Q4.o
	$(CC) -o HW_3_Q4 HW_3_Q4.o

HW_3_Q4.o: HW_3_Q4.c
	$(CC) -c HW_3_Q4.c
